[default]
api_base_url = "https://api.etsy.com"
# data_dir defaults to .etsync/ in project root, with shop name as subdirectory
languages = []  # IETF language tags for translations, e.g. ["de", "fr", "nl"]

# [shop2]
# data_dir = "~/.etsync/data/shop2"
